cdef public object ASyncFlagException
cdef public object NoFlagsFound
cdef public object TooManyFlags
cdef public object InvalidFlag
cdef public object InvalidFlagValue
cdef public object FlagNotDefined
cdef public object FunctionNotSync
cdef public object SyncModeInAsyncContextError
cdef public object PersistedTaskException